language: objective-c
osx_image: xcode9.3
env:
  - DESTINATION="arch=x86_64"                    PLATFORM=Mac  TEST=1
  - DESTINATION="OS=11.3,name=iPhone SE"         PLATFORM=iOS  TEST=1
  - DESTINATION="OS=10.3.1,name=iPhone SE"       PLATFORM=iOS
  - DESTINATION="OS=9.3,name=iPhone 5s"          PLATFORM=iOS
  - DESTINATION="OS=8.4,name=iPhone 4s"          PLATFORM=iOS
  - DESTINATION="OS=11.3,name=Apple TV"          PLATFORM=tvOS  TEST=1
  - DESTINATION="OS=10.2,name=Apple TV 1080p"    PLATFORM=tvOS
  - DESTINATION="OS=9.2,name=Apple TV 1080p"     PLATFORM=tvOS
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLATFORM --verbose
install:
  - xcodebuild -scheme PMKSystemConfiguration -target PMKSystemConfiguration -destination "$DESTINATION" build
  - if [[ $TEST == "1" ]]; then
      xcodebuild -scheme PMKSystemConfiguration -target PMKSCTests -destination "$DESTINATION" build;
    fi
script:
  - if [[ $TEST == "1" ]]; then
      xcodebuild -scheme PMKSystemConfiguration -destination "$DESTINATION" test;
    fi
